comment: off
coverage:
  status:
    project:
      default: off
    statsd:
        flags: statsd
        target: auto
        threshold: 100
        base: auto
    patch:
      default: off
      statsd:
        flags: statsd
        threshold: 100
        base: auto
flags:
  statsd:
    paths:
      - statsd/
